// store/actions.js — Action type constants
export const FormActions = {
  ADD_QUESTION: 'ADD_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  REORDER_QUESTIONS: 'REORDER_QUESTIONS',
  ADD_CHILD_QUESTION: 'ADD_CHILD_QUESTION',
  SET_DEPENDENCY: 'SET_DEPENDENCY',
  REMOVE_DEPENDENCY: 'REMOVE_DEPENDENCY',
  TOGGLE_COLLAPSE: 'TOGGLE_COLLAPSE',
  SET_FORM_META: 'SET_FORM_META',
  LOAD_FORM: 'LOAD_FORM',
  CLEAR_FORM: 'CLEAR_FORM',
};
